#!/bin/sh

ROOT=$(git rev-parse --show-toplevel)
SCRIPTS="$ROOT/scripts"

if [ -f "$ROOT/dev.env" ]; then
	set -o allexport
	source "$ROOT/dev.env"
	set +o allexport
fi

if [ -z "$OPENAI_API_KEY" ]; then
	echo "Missing OPENAI_API_KEY environment variable"
	exit 1
fi

if ! command -v jotbot &> /dev/null; then
	echo "JotBot is not installed. Run 'go install github.com/modernice/jotbot/cmd/jotbot@latest' to install it."
	exit 1
fi

jotbot generate "$ROOT"
